project:
  type: website
  output-dir: docs

website:
  title: "Revegetation Projects"
  navbar:
    title: "Revegetation Projects"
    logo: inyo_logo.png
    left:
      - href: index.qmd
        text: Laws 90/94/95/118/129
      - href: reference.qmd
        text: Reference Parcels
      - icon: github
        href: https://github.com/inyo-gov/revegetation-projects
    background: dark
    search: true
format:
  html:
    theme: bootstrap
    linkcolor: "#2E86AB"
    css: styles.css
    toc: false
    code-fold: true
    code-tools: true
    fig-responsive: true
    table-responsive: false
    fig-dir: figure-html
    subtitle: "Inyo County, California"
    footer: "Â© 2025 Inyo County, California. All rights reserved."

editor: visual